name: CovCysPredictor
channels:
  - conda-forge
  - defaults
dependencies:
  - biopython=1.84=py312h7e5086c_0
  - blas=1.0=openblas
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2024.9.24=hca03da5_0
  - expat=2.6.3=h313beb8_0
  - libcxx=14.0.6=h848a8c0_0
  - libexpat=2.6.3=hf9b8971_0
  - libffi=3.4.4=hca03da5_1
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libopenblas=0.3.21=h269037a_0
  - libsqlite=3.45.2=h091b4b1_0
  - libzlib=1.3.1=hfb2fe0b_1
  - llvm-openmp=14.0.6=hc6e5704_0
  - ncurses=6.4=h313beb8_0
  - numpy=1.26.4=py312h7f4fdc5_0
  - numpy-base=1.26.4=py312he047099_0
  - openssl=3.3.2=h8359307_0
  - pip=24.2=py312hca03da5_0
  - pybind11-abi=5=hd3eb1b0_0
  - python=3.12.2=hdf0ec26_0_cpython
  - python_abi=3.12=5_cp312
  - readline=8.2=h1a28f6b_0
  - scipy=1.13.1=py312ha409365_0
  - setuptools=75.1.0=py312hca03da5_0
  - sqlite=3.45.2=hf2abe2d_0
  - tk=8.6.13=h5083fa2_1
  - tzdata=2024a=h04d1e81_0
  - wheel=0.44.0=py312hca03da5_0
  - xz=5.4.6=h80987f9_1
  - zlib=1.3.1=hfb2fe0b_1
prefix: /opt/anaconda3/envs/CovCysPredictor
